### ISSUE TITLE
Docker installation - import studies example not working (google group)

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal-core#61]
A google group user has reported that the docker importer is not working after following step-by-step docker installation.  User reports that there is a problem with urllib3.  Based on stacktrace, looks like there may be an issue with validateData.py.

[google group thread](https://groups.google.com/g/cbioportal/c/kVCV3cGGaRU)

`
[+] Running 3/0
 ⠿ Container cbioportal-database-container          Running                                                                                                                                             0.0s
 ⠿ Container cbioportal-session-database-container  Running                                                                                                                                             0.0s
 ⠿ Container cbioportal-session-container           Running                                                                                                                                             0.0s
Traceback (most recent call last):
  File "/usr/local/bin/metaImport.py", line 29, in <module>
    from . import validateData
  File "/core/scripts/importer/validateData.py", line 41, in <module>
    import requests
  File "/usr/local/lib/python3.12/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.12/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/local/lib/python3.12/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
`

**Comment by Phae-atwork** [comment]
Just thought i'd add some extra weight to the issue of packages in the container being broken .
i tried to deploy a newer version as it seems 6.0.15 is a bit old now. 
it fixed this immediate problem, but 6.0.19 had issues of it's own with imports.
(connectivity to mariadb)
